### ISSUE TITLE
/vagrant/rpms not writable during [Download Couchbase RPM]

### ISSUE THREAD

**Issue by risdenk** [kruthar/couchbase-mongodb-benchmark#1]
TASK: [Download Couchbase RPM] ************************************************
failed: [cb1.benchmark] => {"failed": true}
msg: Destination /vagrant/rpms not writable

FATAL: all hosts have already failed -- aborting

**Comment by kruthar** [comment]
Yes, easily reproduced by not having an rpms directory. Just needed to add a task in the Couchbase install play to create that directory before downloading the couchbase rpm.
